# Generated by Django 4.1.7 on 2023-03-04 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bonus', models.PositiveIntegerField(default=0, verbose_name='Aardvarks')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='score points')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('topic', models.CharField(choices=[('Topic 1', 'Topic 1'), ('Topic 2', 'Topic 2'), ('Topic 3', 'Topic 3')], max_length=100)),
                ('duration', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Topic 1', 'Topic 1'), ('Topic 2', 'Topic 2'), ('Topic 3', 'Topic 3')], max_length=100)),
                ('questions', models.ManyToManyField(to='db_management.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_management.question')),
            ],
        ),
    ]
